options:
  url:
    name: Nginx Status
    notes: Default status for of nginx instance. Will reset at some point. At rotate.
    default: http://127.0.0.1/nginx_status
metadata:
  reading:
    precision: 0
  writing:
    precision: 0
  waiting:
    precision: 0
  requests:
    precision: 0
  requests_throughput:
    units: /sec
    precision: 3
