options:
  directory:
    name: directory
    notes: Traget directory
    default: /var/log
  command:
    name: command
    notes: Command which used four counting. Examples: `ls -l | wc -l -2` or `find . -type f | wc -l`
    default: find . -type f | wc -l

metadata:
  count:
    label: Count
    precision: 0

triggers:
  - type: peak
    dname: count
    max_value: 4
