options:
  command:
    name: iostat Command
    notes: The command used to display IO statistics
    default: "iostat -dxk"
  interval:
    name: iostat Interval
    notes: Report current usage as the average over this many seconds.
    default: 5 
  device:
    name: Device
    notes: The device to check, eg 'sda1'. If not specified, last one from iostat -dxk
    default:      
metadata:
  rps:
    label: Reads/sec
  wps:
    label: Writes/sec
  rkbps:
    label: Read kBps
    units: kB/s
  wkbps:
    label: Write kBps
    units: kB/s
  await:
    label: I/O Wait
    units: ms
  svctm:
    label: Service Time
    units: ms
  util:
    label: Utilization
    units: %
 
triggers:
  - type: peak
    dname: util
    max_value: 80%
