--- 
metadata: !map:HashWithIndifferentAccess 
  Seconds Behind Master: !map:HashWithIndifferentAccess 
    units: ""
    delimiter: ","
    larger_is_better: "0"
    precision: "0"
    label: Seconds behind master
  Replication Down Time: !map:HashWithIndifferentAccess 
    units: ""
    delimiter: ","
    larger_is_better: "0"
    precision: "0"
    label: Replication Down Time
triggers: 
- max_value: 60.0
  type: peak
  dname: Seconds Behind Master
  population_size: 0
- max_value: 60.0
  type: plateau
  dname: Seconds Behind Master
  population_size: 0
  duration: 10
- max_value: 2.0
  type: plateau
  dname: Replication Down Time
  population_size: 0
  duration: 10
