options:
  port:
    name: monitoring Port
    notes: By default 80 port is used
    default: 80
  netstat:
    name: netstat Command
    notes: The command used to collect network connections
    default: netstat -an
  awk:
    name: awk script
    notes: This script used to grab results column
    default: awk '{ print $4" "$6 }'
  sort:
    name: sort script
    notes: will be used to sort and group
    default: sort | uniq -c | awk '{print $1\" \"$3}'



metadata:
  closed:
    label: CLOSED
    precision: 0
  listen:
    label: LISTEN
    precision: 0
  syn_sent:
    label: SYN_SENT
    precision: 0
  syn_rcvd:
    label: SYN_RCVD
    precision: 0
  established:
    label: ESTABLISHED
    precision: 0
  close_wait:
    label: CLOSE_WAIT
    precision: 0
  last_ack:
    label: LAST_ACK
    precision: 0
  fin_wait_1:
    label: FIN_WAIT_1
    precision: 0
  fin_wait_2:
    label: FIN_WAIT_2
    precision: 0
  closing:
    label: CLOSING
    precision: 0
  time_wait:
    label: TIME_WAIT
    precision: 0



triggers: 
- max_value: 10000
  type: peak
  dname: established
